DROP TABLE IF EXISTS messages;

DROP TABLE IF EXISTS users;

CREATE TABLE messages (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created TIMESTAMP NOT NULL ,
  text    VARCHAR(255) NOT NULL ,
  user_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name     VARCHAR(255) NOT NULL ,
  password VARCHAR(255) NOT NULL ,
  PRIMARY KEY (id)
);

ALTER TABLE messages
  ADD CONSTRAINT fk_messages_user FOREIGN KEY (user_id) REFERENCES users(id);

CREATE TABLE user_authorities(
  user_id   BIGINT NOT NULL ,
  authority VARCHAR(30) NOT NULL ,
  PRIMARY KEY (user_id, authority),
  CONSTRAINT fk_user_authorities_users FOREIGN KEY (user_id) REFERENCES users(id)
);
