DROP TABLE IF EXISTS messages;

DROP TABLE IF EXISTS users;

CREATE TABLE messages (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created TIMESTAMP NOT NULL ,
  text    VARCHAR(255) NOT NULL ,
  user_id BIGINT NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE users (
  id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name     VARCHAR(255) NOT NULL ,
  password VARCHAR(255) NOT NULL ,
  PRIMARY KEY (id)
);

ALTER TABLE messages
  ADD CONSTRAINT fk_messages_user FOREIGN KEY (user_id) REFERENCES users(id);

CREATE TABLE user_authorities(
  user_id   BIGINT NOT NULL ,
  authority VARCHAR(30) NOT NULL ,
  PRIMARY KEY (user_id, authority),
  CONSTRAINT fk_user_authorities_users FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE applications (
  client_id     VARCHAR(63)  NOT NULL,
  client_secret VARCHAR(127) NOT NULL,
  name          VARCHAR(63)  NOT NULL,
  user_id       BIGINT       NOT NULL,
  redirect_uri  VARCHAR(512) NOT NULL,
  PRIMARY KEY (client_id)
);

ALTER TABLE applications
  ADD CONSTRAINT fk_application_users FOREIGN KEY (user_id) REFERENCES users;

CREATE TABLE authorization_codes (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY,
  code      VARCHAR(40),
  created   TIMESTAMP,
  client_id VARCHAR(63) NOT NULL,
  user_id   BIGINT       NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE authorization_codes
  ADD CONSTRAINT fk_authorization_codes_applications FOREIGN KEY (client_id) REFERENCES applications;
ALTER TABLE authorization_codes
  ADD CONSTRAINT fk_authorization_codes_users FOREIGN KEY (user_id) REFERENCES users;

CREATE TABLE authorized_scopes(
  auth_code_id   BIGINT NOT NULL ,
  scope VARCHAR(30) NOT NULL ,
  PRIMARY KEY (auth_code_id, scope),
  CONSTRAINT fk_authorized_scopes_authorization_codes FOREIGN KEY (auth_code_id) REFERENCES authorization_codes(id)
);

CREATE TABLE tokens (
  id                 BIGINT GENERATED BY DEFAULT AS IDENTITY,
  created            TIMESTAMP,
  access_token       VARCHAR(255) NOT NULL ,
  refresh_token      VARCHAR(255) NOT NULL ,
  auth_code_id       BIGINT NOT NULL,
  PRIMARY KEY (id)
);

ALTER TABLE tokens
  ADD CONSTRAINT fk_tokens_authorization_codes FOREIGN KEY (auth_code_id) REFERENCES authorization_codes(id);
